- Refactored to cmd CI job

diff --git a/.github/workflows/cmd.yml b/.github/workflows/cmd.yml
--- a/.github/workflows/cmd.yml
+++ b/.github/workflows/cmd.yml
@@ -1,4 +1,4 @@
-name: Update Typescript API Augment by Comment Command
+name: PR comment bot (/cmd)
 
 on:
   issue_comment:
@@ -12,19 +12,12 @@ permissions:
   contents: write
 
 jobs:
-  update_typescript_api_augment:
-    env:
-      TMP_TARGET: "/tmp/target"
-      CARGO_TARGET_DIR: "target"
-      RUSTC_WRAPPER: "sccache"
-      CARGO_INCREMENTAL: "0"
-      SCCACHE_CACHE_SIZE: "100GB"
-      SCCACHE_GHA_ENABLED: "true"
-    # TODO: Test once it merged to main
-    #    if: github.event.comment.body == '/generate-ts-api' }}
+  is-org-member:
+    # TODO: Uncomment before merge
+    # if: startsWith(github.event.comment.body, '/cmd')
     runs-on: self-hosted
     steps:
-      - name: Check Permission via GraphQL
+      - name: Check Permissions
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           ORG: moondance-labs
@@ -40,9 +33,38 @@ jobs:
           if [[ "$permission_level" == "write" || "$permission_level" == "admin" ]]; then
             echo "✅ User $COLLABORATOR has permission: "$permission_level". Proceeding..."
           else
-            echo "❌ User $COLLABORATOR doesn't have permission: "$permission_level". Failing..." && exit 1
+            echo "❌ User $COLLABORATOR doesn't have enough permission: "$permission_level". Failing..." && exit 1
           fi
+  acknowledge:
+    # TODO: Uncomment before merge
+    # if: ${{ startsWith(github.event.comment.body, '/cmd') }}
+    needs: ["is-org-member"]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Add reaction to triggered comment
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            github.rest.reactions.createForIssueComment({
+              comment_id: ${{ github.event.comment.id }},
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              content: 'eyes'
+            })
 
+  update_typescript_api_augment:
+    needs: ["is-org-member"]
+    env:
+      TMP_TARGET: "/tmp/target"
+      CARGO_TARGET_DIR: "target"
+      RUSTC_WRAPPER: "sccache"
+      CARGO_INCREMENTAL: "0"
+      SCCACHE_CACHE_SIZE: "100GB"
+      SCCACHE_GHA_ENABLED: "true"
+    # TODO: Uncomment before merge
+    #    if: github.event.comment.body == '/cmd generate-ts-api' }}
+    steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
@@ -64,6 +86,7 @@ jobs:
           node-version: 22.x
           cache: "pnpm"
 
+      # TODO: Extract to workflow template and re-use in other workflows (separate PR)
       - name: "Generate Local interfaces"
         run: |
           chmod uog+x target/release/tanssi-node
