Update coverage.yml

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -60,11 +60,12 @@ jobs:
           echo "RUSTFLAGS=-C opt-level=3 -D warnings -C instrument-coverage -C linker=clang -C link-arg=-fuse-ld=$(pwd)/mold/bin/mold" >> $GITHUB_ENV
           # Disable coverage when building
           echo "LLVM_PROFILE_FILE=/dev/null" >> $GITHUB_ENV
-          # TODO: For testing, clean up .cargo, remove this line before merging:
-          #find $HOME/.cargo -type f -name \*.profraw -delete
+          # TODO: For testing, clean up .cargo, remove this lines before merging:
           find $HOME/.cargo -type f -name \*.profraw -print0 | \
-            tee >(xargs -0 du -ch | grep total$) | \
-            xargs -0 rm
+              tee >(xargs -0 echo | wc -w | xargs echo -n >&2; echo " files" >&2) | \
+              du --files0-from=- -ch | \
+              grep total$
+          find $HOME/.cargo -type f -name \*.profraw -delete
       - name: Setup grcov
         run: |
           wget https://github.com/mozilla/grcov/releases/download/v${{ env.GRCOV_VERSION }}/grcov-x86_64-unknown-linux-gnu.tar.bz2
