First try at comparing apis (#1200)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -900,6 +900,64 @@ jobs:
                   pnpm install
                   pnpm moonwall test zombie_${{ matrix.chains.chain }}_upgrade
 
+    check-runtime-api-differences:
+        if: contains(github.event.pull_request.labels.*.name, 'dependency-upgrade')
+        runs-on: ubuntu-latest
+        needs: ["set-tags", "build"]
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v4
+              with:
+                  ref: ${{ needs.set-tags.outputs.git_ref }}
+            - name: Pnpm
+              uses: pnpm/action-setup@v4.1.0
+              with:
+                  version: 9
+            - name: Setup node
+              uses: actions/setup-node@v4
+              with:
+                  node-version: 22.x
+                  cache: "pnpm"
+            - name: Create local folders
+              run: |
+                  mkdir -p test/tmp
+            - name: "Download binaries"
+              uses: actions/download-artifact@v4
+              with:
+                  name: binaries
+                  path: target/release
+            - name: Make binaries executable
+              uses: ./.github/workflow-templates/make-binaries-executable
+
+            - name: Install dependencies
+              run: |
+                cd test
+                pnpm install
+
+            - name: Run comparison
+              run: |
+                cd test
+                ./scripts/run-check-api-diff-job.sh
+
+    confirm-required-jobs-passed-dependency-upgrade:
+      runs-on: ubuntu-latest
+      name: All tests passed
+      # If any new job gets added, be sure to add it to this array
+      needs:
+        [
+          check-runtime-api-differences
+        ]
+      if: always() && !cancelled()
+      steps:
+        - run: |
+            tee resultfile <<< '${{ toJSON(needs) }}'
+            FAILURES=$(cat resultfile | grep '"result": "failure"' | wc -l)
+            if [ $FAILURES -gt 0 ]; then
+              echo "### At least one required job failed ❌" >> $GITHUB_STEP_SUMMARY
+              exit 1
+            else
+              echo '### Good job! All the required jobs passed 🚀' >> $GITHUB_STEP_SUMMARY
+            fi
     docker-tanssi:
         runs-on: ubuntu-latest
         needs: ["set-tags", "build"]
