compare apis job

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -900,6 +900,81 @@ jobs:
                   pnpm install
                   pnpm moonwall test zombie_${{ matrix.chains.chain }}_upgrade
 
+    check-runtime-api-differences:
+        if: contains(github.event.pull_request.labels.*.name, 'dependency-upgrade')
+        runs-on: ubuntu-latest
+        needs: ["set-tags", "build"]
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v4
+              with:
+                  ref: ${{ needs.set-tags.outputs.git_ref }}
+            - name: Pnpm
+              uses: pnpm/action-setup@v4.1.0
+              with:
+                  version: 9
+            - name: Setup node
+              uses: actions/setup-node@v4
+              with:
+                  node-version: 22.x
+                  cache: "pnpm"
+            - name: Create local folders
+              run: |
+                  mkdir -p test/tmp
+            - name: "Download binaries"
+              uses: actions/download-artifact@v4
+              with:
+                  name: binaries
+                  path: target/release
+            - name: Make binaries executable
+              uses: ./.github/workflow-templates/make-binaries-executable
+
+            - name: Download polkadot binary
+              run: |
+                ./test/scripts/download-polkadot.sh
+
+            - name: Get westend api data
+              run: |
+                cd test
+                ./tmp/polkadot --chain=westend-dev --ws-port 341000 > binA.log 2>&1 &
+                echo $! > westend.pid
+                sleep 10  # Wait for node to be ready
+                pnpm get-api-info tmp/westend-api.json --url ws://127.0.0.1:34100
+                kill $(cat westend.pid)
+
+            - name: Get dancelight api data
+              run: |
+                cd test
+                ../target/release/tanssi-relay --chain=dancelight-dev --ws-port 341000 > binA.log 2>&1 &
+                echo $! > dancelight.pid
+                sleep 10  # Wait for node to be ready
+                cd test
+                pnpm get-api-info tmp/dancelight-api.json --url ws://127.0.0.1:34100
+                kill $(cat dancelight.pid)
+
+            - name: Compare
+              run: |
+                ./test/scripts/compare-apis.sh  test/tmp/westend-api.json test/tmp/dancelight-api.json
+
+    confirm-required-jobs-passed-dependency-upgrade:
+      runs-on: ubuntu-latest
+      name: All tests passed
+      # If any new job gets added, be sure to add it to this array
+      needs:
+        [
+          check-runtime-api-differences
+        ]
+      if: always() && !cancelled()
+      steps:
+        - run: |
+            tee resultfile <<< '${{ toJSON(needs) }}'
+            FAILURES=$(cat resultfile | grep '"result": "failure"' | wc -l)
+            if [ $FAILURES -gt 0 ]; then
+              echo "### At least one required job failed ❌" >> $GITHUB_STEP_SUMMARY
+              exit 1
+            else
+              echo '### Good job! All the required jobs passed 🚀' >> $GITHUB_STEP_SUMMARY
+            fi
     docker-tanssi:
         runs-on: ubuntu-latest
         needs: ["set-tags", "build"]
