Better error reporting

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -354,7 +354,14 @@ jobs:
             ref: ${{ needs.set-tags.outputs.git_ref }}
         - name: Retrieve runtime diff
           run: |
-            ./tools/show-me-the-weights.py diff ${{ github.event.pull_request.base.sha }} | tee runtime_size_report.md
+            ./tools/show-me-the-weights.py diff ${{ github.event.pull_request.base.sha }} > runtime_size_report.md \
+            || {
+              # print error in case of failure
+              rc=$?
+              cat runtime_size_report.md
+              exit $rc
+            }
+            cat runtime_size_report.md
         - name: Check for report content
           # set HAS_REPORT=true if file has any bytes, else false
           run: |
