- Fixed permission check

diff --git a/.github/workflows/update-typescript-api-augment.yml b/.github/workflows/update-typescript-api-augment.yml
--- a/.github/workflows/update-typescript-api-augment.yml
+++ b/.github/workflows/update-typescript-api-augment.yml
@@ -28,13 +28,12 @@ jobs:
             -H "Accept: application/vnd.github+json" \
             "https://api.github.com/repos/$ORG/$REPO/collaborators/$COLLABORATOR/permission")
           
-          echo "Permissions: $permissions"
+          permission_level=$(echo "$permissions" | jq -r '.permission')
           
-          if [[ -n "$USER_EXISTS" ]]; then
-            echo "❌ Collaborator $COLLABORATOR is not a contributor, failing..."
-            exit 1
+          if [[ "$permission_level" == "write" || "$permission_level" == "admin" ]]; then
+            echo "✅ User $COLLABORATOR has access to proceed with this job"
           else
-            echo "✅ Collaborator $COLLABORATOR is a contributor. Granting the access to proceed..."
+            echo "❌ User $COLLABORATOR has not access to proceed. Failing..." && exit 1
           fi
 
       - name: Checkout
