- Updated wordings

diff --git a/.github/workflows/update-typescript-api-augment.yml b/.github/workflows/update-typescript-api-augment.yml
--- a/.github/workflows/update-typescript-api-augment.yml
+++ b/.github/workflows/update-typescript-api-augment.yml
@@ -31,9 +31,9 @@ jobs:
           permission_level=$(echo "$permissions" | jq -r '.permission')
           
           if [[ "$permission_level" == "write" || "$permission_level" == "admin" ]]; then
-            echo "✅ User $COLLABORATOR has access to proceed with this job"
+            echo "✅ User $COLLABORATOR has permission $permission_level. Proceeding..."
           else
-            echo "❌ User $COLLABORATOR has not access to proceed. Failing..." && exit 1
+            echo "❌ User $COLLABORATOR doesn't have permission. Failing..." && exit 1
           fi
 
       - name: Checkout
